---

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: hifis.unattended_upgrades
      unattended_automatic_reboot: true
      unattended_automatic_reboot_time: "07:00"
      unattended_remove_unused_dependencies: true
      unattended_remove_new_unused_dependencies: true
      when: ansible_distribution in ['Ubuntu']
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: true
  roles:
    - role: k3s/master

- hosts: node
  become: true
  roles:
    - role: k3s/node
