---
- name: Install K3s Cluster
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: hifis.unattended_upgrades
      unattended_automatic_reboot: true
      unattended_automatic_reboot_time: "07:00"
      unattended_remove_unused_dependencies: true
      unattended_remove_new_unused_dependencies: true
      when: ansible_distribution in ['Ubuntu']
    - role: prereq
    - role: download
    - role: raspberrypi

- name: Make the node K3s main node
  hosts: master
  become: true
  roles:
    - role: k3s_master

- name: Make all nodes K3s worker nodes
  hosts: node
  become: true
  roles:
    - role: k3s_node
